version: '3.2'
services:
  web:
    build: ./php-server
    container_name: dev.site
    depends_on:
      - composer
    links:
      - composer
    environment:
    - APACHE_RUN_USER=www-data
    volumes:
    - type: bind
      source: ./src/site
      target: /var/www/site/
    - type: bind
      source: ./config/sites-enabled/dev.site.conf
      target: /etc/apache2/sites-enabled/dev.site.conf
    - type: bind
      source: ./config/php/php.ini-development
      target: /etc/php/7.0/apache2/php.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/apache2/conf.d/20-xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/apache2/conf.d/20-yaml.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/cli/conf.d/20-xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/cli/conf.d/20-yaml.ini
    - type: bind
      source: ./config/xdebug/docker-php-ext-xdebug.ini
      target: /etc/php/7.0/mods-available/xdebug.ini
    - type: bind
      source: ./config/yaml/yaml.ini
      target: /etc/php/7.0/mods-available/yaml.ini
    - type: bind
      source: ./logs/apache-logs
      target: /var/log/apache2
    ports:
    - 80:80
    networks:
      dev:
        ipv4_address: 172.16.240.10
    working_dir: /var/www/site
    extra_hosts:
    - dev.site:127.0.0.1

  composer:
    build: ./composer
    container_name: composer
    volumes:
    - type: bind
      source: ./src/site
      target: /var/www/site/
    working_dir: /var/www/site/
    command: bash -c "composer install"

  node:
    image: node:8-slim
    container_name: node
    depends_on:
      - composer
    links:
      - composer
    volumes:
    - type: bind
      source: ./src/site
      target: /var/www/site/
    - type: bind
      source: ./logs/npm
      target: /root/.npm/_logs
    working_dir: /var/www/site/
    command: bash -c "apt-get update && apt-get install -y build-essential libpng-dev && yarn install && npm run watch"

networks:
  dev:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.16.240.0/24
